name: 'Project activity metrics'
description:
  'Transfer issues between repositories using labels, including private to
  public transfers.'
author: 'fgerthoffert'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: green

# Define your inputs here.
inputs:
  token:
    description: 'A GitHub Personal API Token'
    required: true
  config:
    description: 'Configuration file path'
    required: true
  github_org_name:
    description: 'The GitHub organization name'
    required: true
  github_project_number:
    description: 'A project number inside the organization'
    required: true
  dev_cache:
    description:
      'Enable development cache, this prevents the action from fetching data
      from GitHub too frequently'
    required: true
    default: false
  views_output_path:
    description: 'Filepath where the dashboards will be saved'
    required: true

runs:
  using: node20
  main: dist/index.js
